"""DropPosterIdInteraction

Revision ID: 007db474143e
Revises: 339bd9c8a2f8
Create Date: 2023-12-26 13:26:57.271085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007db474143e'
down_revision: Union[str, None] = '339bd9c8a2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Interaction', 'PosterId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Interaction', sa.Column('PosterId', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###
