"""init

Revision ID: 339bd9c8a2f8
Revises: 
Create Date: 2023-12-24 12:32:37.647101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339bd9c8a2f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Interaction',
                    sa.Column('Id', sa.Integer(), nullable=False),
                    sa.Column('ChatId', sa.BigInteger(), nullable=False),
                    sa.Column('PosterId', sa.BigInteger(), nullable=False),
                    sa.Column('MessageId', sa.BigInteger(), nullable=False),
                    sa.Column('UserId', sa.BigInteger(), nullable=False),
                    sa.Column('Reaction', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('Id')
                    )
    op.create_table('Post',
                    sa.Column('Id', sa.Integer(), nullable=False),
                    sa.Column('ChatId', sa.BigInteger(), nullable=False),
                    sa.Column('PosterId', sa.BigInteger(), nullable=False),
                    sa.Column('MessageId', sa.BigInteger(), nullable=False),
                    sa.Column('Timestamp', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('Id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IX_Interaction_ChatId', table_name='Interaction')
    op.drop_index('IX_Interaction_MessageId', table_name='Interaction')
    op.drop_index('IX_Interaction_PosterId', table_name='Interaction')
    op.drop_index('IX_Interaction_UserId', table_name='Interaction')
    op.drop_table('Interaction')
    op.drop_index('IX_Post_ChatId', table_name='Post')
    op.drop_index('IX_Post_MessageId', table_name='Post')
    op.drop_index('IX_Post_PosterId', table_name='Post')
    op.drop_index('IX_Post_Timestamp', table_name='Post')
    op.drop_table('Post')
    # ### end Alembic commands ###
