"""init

Revision ID: 339bd9c8a2f8
Revises: 
Create Date: 2023-12-24 12:32:37.647101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339bd9c8a2f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('poster_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reaction', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('poster_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('IX_Interaction_ChatId', table_name='Interaction')
    op.drop_index('IX_Interaction_MessageId', table_name='Interaction')
    op.drop_index('IX_Interaction_PosterId', table_name='Interaction')
    op.drop_index('IX_Interaction_UserId', table_name='Interaction')
    op.drop_table('Interaction')
    op.drop_index('IX_Post_ChatId', table_name='Post')
    op.drop_index('IX_Post_MessageId', table_name='Post')
    op.drop_index('IX_Post_PosterId', table_name='Post')
    op.drop_index('IX_Post_Timestamp', table_name='Post')
    op.drop_table('Post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('ChatId', sa.INTEGER(), nullable=False),
    sa.Column('PosterId', sa.INTEGER(), nullable=False),
    sa.Column('MessageId', sa.INTEGER(), nullable=False),
    sa.Column('Timestamp', sa.DATETIME(), server_default=sa.text("(datetime('now','localtime'))"), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Post_Timestamp', 'Post', ['Timestamp'], unique=False)
    op.create_index('IX_Post_PosterId', 'Post', ['PosterId'], unique=False)
    op.create_index('IX_Post_MessageId', 'Post', ['MessageId'], unique=False)
    op.create_index('IX_Post_ChatId', 'Post', ['ChatId'], unique=False)
    op.create_table('Interaction',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('ChatId', sa.INTEGER(), nullable=False),
    sa.Column('PosterId', sa.INTEGER(), nullable=False),
    sa.Column('MessageId', sa.INTEGER(), nullable=False),
    sa.Column('UserId', sa.INTEGER(), nullable=False),
    sa.Column('Reaction', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('IX_Interaction_UserId', 'Interaction', ['UserId'], unique=False)
    op.create_index('IX_Interaction_PosterId', 'Interaction', ['PosterId'], unique=False)
    op.create_index('IX_Interaction_MessageId', 'Interaction', ['MessageId'], unique=False)
    op.create_index('IX_Interaction_ChatId', 'Interaction', ['ChatId'], unique=False)
    op.drop_table('post')
    op.drop_table('interaction')
    # ### end Alembic commands ###
